### ISSUE TITLE
cho0-connect-and-express Issue in full app code base in validate.js middleware

### ISSUE THREAD

**Issue by JToaddler** [alexyoung/nodejsinaction#7]
I got the below error when i tried to run the app `ch06-connect-and-express\full-app`. Issue can be recreated when title violate the validation rule.

`TypeError: res.error is not a function
    at D:\Workspace\node\shoutbox2\middleware\validate.js:21:17
    at Layer.handle [as handle_request] (D:\Workspace\node\shoutbox2\node_modules\express\lib\router\layer.js:95:5)
    at next (D:\Workspace\node\shoutbox2\node_modules\express\lib\router\route.js:137:13)
    at Route.dispatch (D:\Workspace\node\shoutbox2\node_modules\express\lib\router\route.js:112:3)
    at Layer.handle [as handle_request] (D:\Workspace\node\shoutbox2\node_modules\express\lib\router\layer.js:95:5)`

**Comment by JToaddler** [comment]
there is no function called error in the response object ?

**Comment by JToaddler** [comment]
there is no error function in the response object.
